// Tiny TCA: CaseKeyPath for key path-like syntax with enum cases

import Foundation

/// A key path-like type that can extract and embed values from enum cases
///
/// CaseKeyPath enables the syntax `\.caseName` for enum cases, similar to how
/// KeyPath enables `\.propertyName` for struct properties.
///
/// This type is typically generated by the `@CasePathable` macro, but can also
/// be created manually for custom use cases.
///
/// Example usage with Scope:
/// ```swift
/// Scope(state: \.child, action: \.child) {
///     ChildReducer()
/// }
/// ```
public struct CaseKeyPath<Root, Value>: Sendable where Root: Sendable, Value: Sendable {
    /// Function to extract the associated value from the enum case
    public let extract: @Sendable (Root) -> Value?

    /// Function to embed a value into the enum case
    public let embed: @Sendable (Value) -> Root

    /// Creates a case key path with extract and embed functions
    ///
    /// - Parameters:
    ///   - extract: A function that attempts to extract a value from the root enum
    ///   - embed: A function that embeds a value into the root enum
    public init(
        extract: @escaping @Sendable (Root) -> Value?,
        embed: @escaping @Sendable (Value) -> Root
    ) {
        self.extract = extract
        self.embed = embed
    }

    /// Converts this CaseKeyPath to a CasePath for use with existing APIs
    public var casePath: CasePath<Root, Value> {
        CasePath(extract: extract, embed: embed)
    }
}

// MARK: - Identity CaseKeyPath

extension CaseKeyPath where Root == Value {
    /// Identity case key path that passes values through unchanged
    public static var `self`: CaseKeyPath<Root, Root> {
        CaseKeyPath(
            extract: { $0 },
            embed: { $0 }
        )
    }
}

// MARK: - Void CaseKeyPath (for cases without associated values)

extension CaseKeyPath where Value == Void {
    /// Creates a case key path for enum cases without associated values
    ///
    /// - Parameters:
    ///   - extract: A function that returns true if the case matches
    ///   - embed: A function that creates the enum case
    public init(
        extract: @escaping @Sendable (Root) -> Bool,
        embed: @escaping @Sendable () -> Root
    ) {
        self.init(
            extract: { extract($0) ? () : nil },
            embed: { _ in embed() }
        )
    }
}

// MARK: - CasePath Conversion

extension CasePath {
    /// Creates a CasePath from a CaseKeyPath
    public init(_ caseKeyPath: CaseKeyPath<Root, Value>) {
        self.init(extract: caseKeyPath.extract, embed: caseKeyPath.embed)
    }
}
