// Tiny TCA: CasePathable protocol for enum case key paths

import Foundation

/// A type that provides case key paths for its enum cases
///
/// Conformance to this protocol is typically generated by the `@CasePathable` macro.
/// The macro generates an `AllCasePaths` struct containing a `CaseKeyPath` for each
/// enum case, enabling the `\.caseName` syntax.
///
/// Example:
/// ```swift
/// @CasePathable
/// enum Action {
///     case increment
///     case child(ChildAction)
/// }
///
/// // Generated AllCasePaths struct enables:
/// let path = Action.allCasePaths.child  // CaseKeyPath<Action, ChildAction>
/// ```
///
/// With `@dynamicMemberLookup`, you can use shorter syntax:
/// ```swift
/// let path: CaseKeyPath<Action, ChildAction> = \.child
/// ```
public protocol CasePathable {
    /// A type containing all case key paths for this enum
    associatedtype AllCasePaths

    /// The collection of all case key paths
    static var allCasePaths: AllCasePaths { get }
}

// MARK: - Dynamic Member Lookup Support

/// Enables `\.caseName` syntax for CasePathable types
///
/// This allows writing:
/// ```swift
/// Scope(state: \.counter, action: \.counter) { ... }
/// ```
/// Instead of:
/// ```swift
/// Scope(state: \.counter, action: Action.allCasePaths.counter) { ... }
/// ```
@dynamicMemberLookup
public struct AnyCasePath<Root: CasePathable> {
    /// Looks up a case key path by name
    public subscript<Value>(
        dynamicMember keyPath: KeyPath<Root.AllCasePaths, CaseKeyPath<Root, Value>>
    ) -> CaseKeyPath<Root, Value> {
        Root.allCasePaths[keyPath: keyPath]
    }
}

// MARK: - Key Path Literal Support

/// Enables `\.caseName` syntax in contexts expecting CaseKeyPath
///
/// This extension allows using key path literals to reference case paths
/// when the root type conforms to CasePathable.
extension CaseKeyPath where Root: CasePathable {
    /// Creates a CaseKeyPath from a key path into AllCasePaths
    ///
    /// This initializer enables the `\.caseName` syntax:
    /// ```swift
    /// let path: CaseKeyPath<Action, ChildAction> = \.child
    /// ```
    public init(_ keyPath: KeyPath<Root.AllCasePaths, CaseKeyPath<Root, Value>>) {
        self = Root.allCasePaths[keyPath: keyPath]
    }
}
